In [1]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [2]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]],dtype = complex)
print(x)

[[10.+0.j 20.+0.j 30.+0.j]
 [40.+0.j 50.+0.j 60.+0.j]
 [70.+0.j 80.+0.j 90.+0.j]]


In [3]:
import numpy as np
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]],dtype = float)
print(x)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [6]:
#zero() and ones()
y =np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
y =np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
x = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print("Row 0:",x[0])
print("Row 1:",x[1])

Row 0: [10 20 30]
Row 1: [40 50 60]


In [10]:
print(x[0:2])

[[10 20 30]
 [40 50 60]]


In [11]:
print(x[::-1])

[[70 80 90]
 [40 50 60]
 [10 20 30]]
